name: Run playwright script

on:
  workflow_dispatch: # 当手动触发时执行工作流程

jobs:
  execute_playwright_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Playwright dependencies
      run: npm install playwright
    
    - name: Run Playwright script
      run: node main/dengQG.pw.js # 指定脚本文件的路径
    
    - name: Save screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshot.png # 生成的截图文件
        
    - name: Save cookies
      uses: actions/upload-artifact@v2
      with:
        name: cookies
        path: qianguocookies1.json # 生成的 cookies 文件
